#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"
echo 'Fazendo verificações de código com sonar-scanner. Certifique-se que o sonarqube esteja ativo'
sh run-sonar.sh
echo 'Análise concluida com sucesso!'

echo 'Chegando erros no código antes do commit :)'
npx eslint src


